#!/usr/bin/env bash

# METHOD FOR THIS DEFINITELY INFLUENCED BY MIKE@LinuxDabbler on YT!

# directory variable
qtilevenv="$HOME/.local/src/qtile_venv"

# Dependencies
sudo apt install -y python3 python3-pip python3-venv python3-v-sim python-dbus-dev libpangocairo-1.0-0 python3-cairocffi python3-xcffib libxkbcommon-dev libxkbcommon-x11-dev git sxhkd

# Setting up virtual environment for qtile.
python3 -m venv $qtilevenv 
mkdir ~/.local/bin/

# Git clone into virtual environment
git clone https://github.com/qtile/qtile.git $qtilevenv/qtile

# Install Qtile
$qtilevenv/bin/pip install $qtilevenv/qtile/.

# Install psutil
$qtilevenv/bin/pip install psutil

# Adding venv to correct path ~/.local/bin/qtile

ln -sf $qtilevenv/bin/qtile ~/.local/bin/

# Adding qtile.desktop to Lightdm xsessions directory
cat > ./temp << "EOF"
[Desktop Entry]
Name=Qtile
Comment=Qtile Session
Type=Application
Keywords=wm;tiling
EOF
sudo cp ./temp /usr/share/xsessions/qtile.desktop;rm ./temp
u=$USER
sudo echo "Exec=/home/$u/.local/bin/qtile start" | sudo tee -a /usr/share/xsessions/qtile.desktop
